language: php

sudo: false

php:
  - 7
  - 5.6
  - 5.5
  - 5.4

before_script:
  - composer install
  
script:
  - php vendor/bin/phpcs --standard=./test/codesniffer.xml -s --encoding=utf-8 ./src
  - php vendor/bin/phpunit -c test/phpunit.xml --coverage-text
