name: Tests
on: [push, pull_request]

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Perform phpunit tests
        uses: ./containers/run_php_tests
